// ÜRETİLMİŞ DOSYA — ELLE DÜZENLEME.
//
// Kaynak: dima-backend app/schemas.py → schema/openapi.json
// Yenile: bun run --filter @dima/contracts codegen
// CI, bu dosyanın güncel olduğunu 'codegen:check' ile doğrular.
//
// SINIRI BİL: backend bazı alanları `dict[str, Any]` olarak tiplemiş
// (kpi, interpretation, cube_query). Onlar burada Record<string, unknown>
// olarak çıkar — işe yaramaz. O alanların KULLANILABİLİR şekilleri
// src/types.ts'te elle yazılıdır ve orada kalmalıdır. Codegen ancak
// backend'in tiplediği kadar iyidir.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @description Natural-language question (Turkish or English).
             */
            question: string;
            /**
             * Limit
             * @default null
             */
            limit: number | null;
            /**
             * Execute
             * @description If false, only generate + validate SQL.
             * @default true
             */
            execute: boolean;
            /** History */
            history?: string[];
            /**
             * Cube Query
             * @default null
             */
            cube_query: Record<string, never> | null;
            /**
             * Session Id
             * @default null
             */
            session_id: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Question */
            question: string;
            /**
             * Sql
             * @default
             */
            sql: string;
            /**
             * Planned Sql
             * @default null
             */
            planned_sql: string | null;
            /** @default null */
            result: components["schemas"]["QueryResult"] | null;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /**
             * Cube Query
             * @default null
             */
            cube_query: Record<string, never> | null;
            /**
             * Note
             * @default null
             */
            note: string | null;
            /** Trace */
            trace?: string[];
            /** Suggestions */
            suggestions?: components["schemas"]["Suggestion"][];
            /**
             * View Hint
             * @default null
             */
            view_hint: string | null;
            /**
             * Contract Id
             * @default null
             */
            contract_id: string | null;
            /**
             * Kpi
             * @default null
             */
            kpi: Record<string, never> | null;
            /**
             * Interpretation
             * @default null
             */
            interpretation: Record<string, never> | null;
            /** Next Steps */
            next_steps?: components["schemas"]["NextStep"][];
            /** Recommendations */
            recommendations?: components["schemas"]["Recommendation"][];
        };
        /** ColumnMeta */
        ColumnMeta: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Values
             * @default null
             */
            values: string[] | null;
        };
        /**
         * ConversationDetail
         * @description Tek sohbet + mesajları — resume için. messages = ham AskResponse payload'ları
         *     (frontend doğrudan render eder; yeniden çalıştırma yok).
         */
        ConversationDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Session Id */
            session_id: string;
            /** Messages */
            messages: Record<string, never>[];
        };
        /**
         * ConversationOut
         * @description Sohbet listesi öğesi (geçmiş kenar çubuğu).
         */
        ConversationOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Session Id */
            session_id: string;
            /** Message Count */
            message_count: number;
            /** Updated At */
            updated_at: string;
        };
        /**
         * CubeRequest
         * @description Yorum çubuğu (chip) düzenlemesi: client CubeQuery'yi doğrudan düzenler,
         *     motor deterministik çalıştırır (LLM yok). label: transkriptte görünen açıklama.
         */
        CubeRequest: {
            /** Cube Query */
            cube_query: Record<string, never>;
            /**
             * Label
             * @default null
             */
            label: string | null;
            /**
             * Limit
             * @default null
             */
            limit: number | null;
            /**
             * Session Id
             * @default null
             */
            session_id: string | null;
            /**
             * Verdict
             * @default null
             */
            verdict: string | null;
            /**
             * Undo
             * @default false
             */
            undo: boolean;
            /**
             * Comment
             * @default null
             */
            comment: string | null;
        };
        /** ModelMeta */
        ModelMeta: {
            /** Name */
            name: string;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
        };
        /**
         * NextStep
         * @description K2 (rehberli analitik) — bir rapordan DETERMİNİSTİK 'sonraki adım' chip'i. label
         *     gösterilir; tıklanınca TAM cube_query `/cube` ile LLM'siz koşar (drill-down/ölçek/zaman).
         *     kind = dimension (kırılım) | measure (ölçek) | time (granülerlik) — FE gruplama/renk için.
         */
        NextStep: {
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Cube Query */
            cube_query: Record<string, never>;
        };
        /** QueryRequest */
        QueryRequest: {
            /**
             * Sql
             * @description SQL SELECT executed through the Wren semantic layer.
             */
            sql: string;
            /**
             * Limit
             * @description Optional row cap.
             * @default null
             */
            limit: number | null;
        };
        /** QueryResult */
        QueryResult: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: Record<string, never>[];
            /** Row Count */
            row_count: number;
        };
        /**
         * Recommendation
         * @description K4 (karar motoru) — bir SİNYALDEN (K3) türetilen aksiyon önerisi: "neye bakmalısın".
         *     text = deterministik öneri cümlesi; action opsiyonel = tıklanınca koşan drill (K2 reuse)
         *     — böylece içgörü→öneri→AKSİYON tek tıkla kapanır.
         */
        Recommendation: {
            /** Text */
            text: string;
            /** @default null */
            action: components["schemas"]["NextStep"] | null;
        };
        /** RelationshipMeta */
        RelationshipMeta: {
            /** Name */
            name: string;
            /** Models */
            models: string[];
            /**
             * Join Type
             * @default
             */
            join_type: string;
            /**
             * Condition
             * @default
             */
            condition: string;
        };
        /** SchemaResponse */
        SchemaResponse: {
            /**
             * Catalog
             * @default null
             */
            catalog: string | null;
            /**
             * Schema Name
             * @default null
             */
            schema_name: string | null;
            /** Models */
            models: components["schemas"]["ModelMeta"][];
            /**
             * Relationships
             * @default []
             */
            relationships: components["schemas"]["RelationshipMeta"][];
            /** Cubes */
            cubes?: Record<string, never>[];
            /**
             * Db Online
             * @default true
             */
            db_online: boolean;
        };
        /**
         * Suggestion
         * @description Tıklanır hızlı-yanıt chip'i: label gösterilir, tıklanınca query gönderilir.
         *     Meta yanıtta örnek sorgular; clarification'da dönem seçenekleri (ADR-0007).
         */
        Suggestion: {
            /** Label */
            label: string;
            /** Query */
            query: string;
        };
        /**
         * UploadRequest
         * @description Chat-scoped Excel/CSV yükleme (base modu). Dosya base64; python-multipart gerektirmez.
         *     Veri oturum DuckDB'sine iner (ephemeral) → oto-cube → mevcut NL pipeline.
         */
        UploadRequest: {
            /** Session Id */
            session_id: string;
            /** Filename */
            filename: string;
            /** Content B64 */
            content_b64: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Dataset */
            dataset: string;
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: Record<string, never>[];
            /** Suggestions */
            suggestions?: components["schemas"]["Suggestion"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AskRequest = components['schemas']['AskRequest'];
export type AskResponse = components['schemas']['AskResponse'];
export type ColumnMeta = components['schemas']['ColumnMeta'];
export type ConversationDetail = components['schemas']['ConversationDetail'];
export type ConversationOut = components['schemas']['ConversationOut'];
export type CubeRequest = components['schemas']['CubeRequest'];
export type ModelMeta = components['schemas']['ModelMeta'];
export type NextStep = components['schemas']['NextStep'];
export type QueryRequest = components['schemas']['QueryRequest'];
export type QueryResult = components['schemas']['QueryResult'];
export type Recommendation = components['schemas']['Recommendation'];
export type RelationshipMeta = components['schemas']['RelationshipMeta'];
export type SchemaResponse = components['schemas']['SchemaResponse'];
export type Suggestion = components['schemas']['Suggestion'];
export type UploadRequest = components['schemas']['UploadRequest'];
export type UploadResponse = components['schemas']['UploadResponse'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
